name: Build Nuxt3 Application

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm install

            - name: Copy configuration file
              run: cp SAMPLE.app.config.ts app.config.ts

            - name: Generate static site
              run: npm run generate
